# Generated by Django 4.1.13 on 2024-03-12 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('adress', models.CharField(default='', max_length=500)),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('tel', models.CharField(default='', max_length=255, null=True, unique=True)),
                ('joining_Date', models.DateField(default=django.utils.timezone.now)),
                ('numOfProjects', models.IntegerField(default=0)),
                ('customer_photo', models.ImageField(default='customer_photos/', upload_to='customer_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='customer_files')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
