# Generated by Django 4.1.13 on 2024-05-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='numOfProjects',
        ),
    ]
