# Generated by Django 4.1.13 on 2024-04-25 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_start', models.DateField(blank=True)),
                ('tt_end', models.DateField(blank=True)),
                ('number_of_days', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
