# Generated by Django 4.1.13 on 2024-04-30 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_day', models.DateField(blank=True)),
                ('exit_start', models.TimeField(blank=True)),
                ('exit_end', models.TimeField(blank=True)),
                ('number_of_hours', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_exit_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
