# Generated by Django 4.1.13 on 2024-03-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='timesheets.timesheet'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='billable',
            field=models.BooleanField(default=True),
        ),
    ]
