# Generated by Django 4.1.13 on 2024-03-26 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
        ('timesheets', '0004_alter_timesheet_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='billablehours',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='notbillablehours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('employee', 'project', 'date')},
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='billable',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='hours',
        ),
    ]
