# Generated by Django 4.1.13 on 2024-04-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_task_billable_timesheet_billablehours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(),
        ),
    ]
