# Generated by Django 4.1.13 on 2024-04-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_alter_task_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'permissions': [('import_timesheet', 'Can import timesheet'), ('export_timesheet', 'Can export timesheet')]},
        ),
    ]
