# Generated by Django 5.0.2 on 2024-05-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half Day', 'Half Day'), ('Remote', 'Remote'), ('Permission', 'Permission')], max_length=20),
        ),
    ]
