# Generated by Django 5.0.2 on 2024-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half Day', 'Half Day'), ('Remote', 'Remote'), ('Permission', 'Permission'), ('Leave', 'Leave')], max_length=20),
        ),
    ]
