# Generated by Django 4.1.13 on 2024-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='asset',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Mouse', 'Mouse'), ('Phone', 'Phone'), ('Headset', 'Headset'), ('SIM Card', 'SIM Card'), ('Licence', 'Licence')], max_length=100, unique=True),
        ),
    ]
