# Generated by Django 4.1.13 on 2024-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_asset_alter_user_assets_alter_userasset_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Simple User', 'Simple User'), ('Admin', 'Admin'), ('Talent Management', 'Talent Management'), ('Scrum Master', 'Scrum Master'), ('General Manager', 'General Manager')], default='Simple User', max_length=255),
        ),
    ]
