# Generated by Django 4.1.13 on 2024-05-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userasset',
            name='category',
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='rib',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
