# Generated by Django 4.1.13 on 2024-05-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_user_permissions_role_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
    ]
