# Generated by Django 4.1.13 on 2024-05-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_no',
            field=models.CharField(default='', max_length=32),
        ),
    ]
