# Generated by Django 4.1.13 on 2024-03-12 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Completed', 'Completed'), ('Paused', 'Paused')], default='Active', max_length=50)),
                ('starter_at', models.DateTimeField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('abbreviation', models.CharField(default='', max_length=10, null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploadFiles')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('abbreviation', models.CharField(max_length=10, null=True, default=''))
            ],
        ),
    ]
