# Generated by Django 4.1.13 on 2024-05-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_manager_project_project_manager_and_more'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('InProgress', 'InProgress'), ('ToDo', 'ToDo'), ('Canceled', 'Canceled'), ('OnHold', 'OnHold'), ('Review', 'Review')], default='ToDo', max_length=255),
        ),
    ]
