# Generated by Django 4.1.13 on 2024-05-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_project_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('InProgress', 'InProgress'), ('ToDo', 'ToDo'), ('Canceled', 'Canceled'), ('OnHold', 'OnHold'), ('Review', 'Review')], default='ToDo', max_length=255),
        ),
    ]
