# Generated by Django 4.1.13 on 2024-05-27 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetingroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroom',
            name='createdate',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='room',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='status',
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='Absorption_capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='MeetingroomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('reservation_start', models.TimeField(blank=True)),
                ('reservation_end', models.TimeField(blank=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], max_length=255)),
                ('creator', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meeringroom', to='meetingroom.meetingroom')),
            ],
        ),
    ]
