# Generated by Django 4.1.13 on 2024-05-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingroom', '0002_remove_meetingroom_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='name',
            field=models.TextField(default='', unique=True),
        ),
    ]
