# Generated by Django 4.1.13 on 2024-05-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingroom', '0003_alter_meetingroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroomreservation',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], max_length=255, null=True),
        ),
    ]
