# Generated by Django 4.1.13 on 2024-04-16 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('minDays', models.IntegerField(default=1)),
                ('maxDays', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start', models.DateField(blank=True)),
                ('leave_end', models.DateField(blank=True)),
                ('number_of_days', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Approaved', 'Approaved'), ('Declined', 'Declined'), ('Pending', 'Pending')], max_length=10, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
