# Generated by Django 4.1.13 on 2024-05-14 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0003_leave_approvers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='approvers',
        ),
        migrations.CreateModel(
            name='LeaveApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='leaves.leave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
