# Generated by Django 4.1.13 on 2024-05-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_alter_leaveapprover_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapprover',
            name='approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
